version: 0.0
os: linux
files:
  #đường dẫn chạy file mặc định
  - source: /index.html
    destination: /var/www/html/
hooks:
  #script để thực hiện deploy code
  BeforeInstall:
    #script cài packet
    - location: scripts/install_dependencies 
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

